### ISSUE TITLE
Modifiers do not work as primary action of key

### ISSUE THREAD

**Issue by TorC8** [UltimateHackingKeyboard/firmware#166]
I have my shift keys set with shift as primary action and Fn as secondary.  However, shift is only sent to the computer as a tap on release, making the shift key useless to (for example) combine with the mouse.  Confirmed still an issue by checking with xev using FW 8.4.5.

**Comment by mondalaci** [comment]
This is not a bug, but the expected behavior. The primary role is only supposed to trigger momentarily upon key release if a secondary role is set. This is the only behavior that allows us to trigger the secondary role without inadvertently triggering the primary role. You are not supposed to specify a modifier as primary role if also setting a secondary role because it doesn't make sense usability-wise.
