### ISSUE TITLE
Layer deactivation

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#199]
Let's assume following mapping:

- left case button is mapped to "activate mod"
- right case button is mapped to "toggle mod"

Scenario:
- Single tap right button
- Single tap left button

Expected outcome:
- First tap toggles the layer
- Second tap untoggles the layer

Actual outcome:
- The first tap toggles the layer
- Second tap does nothing

Scenario no. 2:
- Doubletap left button
- Tap right button
- Tap right button again

Expected outcome:
- layer toggles
- layer untoggles
- layer toggles again

Actual outcome:
- layer toggles
- layer untoggles
- nothing

What is the reason for checking for `isLayerDoubleTapToggled` on line 214 in usb_report_updater.c? I see no good reason for that and I assume that it is the culprit.

    if (!keyState->previous && isLayerDoubleTapToggled && ToggledLayer == action->switchLayer.layer) {
        ToggledLayer = LayerId_Base;
        isLayerDoubleTapToggled = false;
    }

**Comment by mondalaci** [comment]
Thanks for your report! @eltang will look into this which will likely take a month or two given how busy he is nowadays.

**Comment by owlstead** [comment]
Note that my bug report #194 contains possible ideas for fixes. This is a more generalized and better documented bug report so I closed mine.

**Comment by piratk** [comment]
This annoys me as well. I would like to have these options:
* Tap to toggle layer
* Hold to enable layer
* Tap + 2nd button to toggle layer, for instance "Left space" for Mod layer and "Right case button" to toggle, then "Right case button" could deactivate Mod Layer.
* Using  same button as tap to toggle, holding and pressing any other button on layer would cause the layer to deactivate when tap to toggle button is released.

**Comment by owlstead** [comment]
@piratk Having different ways of switching between layers should be posted as a separate feature request. And yes, for that feature request the switching back and forth between layers should be correct as well. You may want to provide a more detailed description or plan if you do. Let's first fix this issue though.

**Comment by owlstead** [comment]
Note that I have to actively add an "Activate Fn" key to key maps with just toggle to make it even *possible* to switch off Fn after switching key maps. I have to use the activate Fn key to switch key maps. Otherwise I'm stuck in Fn mode, whatever key map I choose, rendering the UHK completely useless and even dangerous.

This seems to be a relatively easy to fix bug (if Fn is active and any Fn key is hit - be it toggle or activate, switch it off, and switch off any modifier key after switching to another key map). A bug fix - just the removal of a single boolean variable - has been proposed in the original report.

Now I do understand that devs can be busy, but it has been easily over 2 months, quickly nearing 3 and multiple firmware releases and this question (including my previous one filed October 22th), but this *feels* like not being taken seriously.

**Comment by kareltucek** [comment]
@mondalaci what is the intended behaviour of layer *deactivations*? 

- Should "standard toggle" action unlock "doubletap toggled" layer?
- Should (simple press of) "doubletaptoggle" action unlock "standard toggled" layer?
- Should "standard hold" action unlock "doubletap toggled" layer?
- Should "standard hold" action unlock "standard toggled" layer?

Current behaviour is`(sometimes, no, no, no)`.

This ticket assumes it should be at least `(yes, no, no, no)`. I am unsure if it shouldn't be `(yes, yes, no, no)` or even `(yes, yes, yes, yes)`.

**Comment by mondalaci** [comment]
What does "standard hold" action mean?

**Comment by kareltucek** [comment]
Agent-wise "Activate layer" without checked "Lock layer when doubletapping this key". Firmware-wise `SwitchLayerMode_Hold`.

**Comment by mondalaci** [comment]
I see. All yes then.

**Comment by kareltucek** [comment]
Alright!
