### ISSUE TITLE
Slow scrolling since Linux 5.0 release?

### ISSUE THREAD

**Issue by bbolgradov** [UltimateHackingKeyboard/firmware#212]
Hi,

Sorry for reporting this, as it may not be an actual issue.

I'm wondering if I'm the only one experiencing this, but since I updated Linux to 5.0 with its "high-resolution scrolling support" the UHK mouse scroll seems to be really slow.

I had to change the Base speed from 20 to ~90 pps to make it work similar to before.
But Windows, on the other hand, scrolls way too fast at the speed of 90. :)

So now I can't decide if it's an UHK firmware issue and there's something you can do or it's a Linux "high-resolution scrolling" configuration issue.

Agent: 8.5.3
Firmware: 8.5.4
OS: Arch Linux x64

PS: I love the keyboard BTW, I just got it with batch 56 last week. Packaging was impressive too! :)

**Comment by mondalaci** [comment]
Hi there, and thanks for the nice words!

It's not a firmware issue. OSes handle the values reported by input devices any way they want, and are free to change their behavior. If you use multiple OSes, the scrolling speed should be set on the OS level in some way, so that it'd match across your OSes. There isn't really any way around this.

I'm closing this, but feel free to follow up.
