### ISSUE TITLE
Feature request: Toggle key state

### ISSUE THREAD

**Issue by justinian** [UltimateHackingKeyboard/firmware#302]
When gaming with my UHK, I often find myself holding down certain keys for extended periods (e.g. Shift and/or W) which is not very friendly to my RSI. I've tried adding macros to hold down keys for me, but the best I can do is: Press key, delay N seconds. The key will be released when the macro ends, even without a Release Key action.

Would it be possible with the current firmware design to have a macro toggle or invert the state of a key such that the UHK reports the key as being held down until it is again toggled off?

**Comment by mondalaci** [comment]
This is not planned, but please take a look at https://github.com/kareltucek/firmware which may implement something like what you're looking for.

**Comment by justinian** [comment]
Thanks, I'll take a look!

**Comment by kareltucek** [comment]
There is no straightforward way to do that even on the fork, since in order to keep a key pressed you need to keep its activation macro alive. To do that, you can use an active wait loop in combination with register signalling, but it will not be trivial to set up... 

If you want to dig further into it, feel free to start a new ticket in the linked repository.

**Comment by justinian** [comment]
Thanks @kareltucek! I'll take a look at the code in your fork and try to get an understanding for it first.
