### ISSUE TITLE
Switching windows of application in Gnome Shell 3.36

### ISSUE THREAD

**Issue by jsporna** [UltimateHackingKeyboard/firmware#310]
I have configured:
Mod + D as Super + Tab (switching application)
Mod + \` as Super + \` (switching windows of application)

Description of keyboard behaves:
I pressed Mod and pressing D until I reach desire application next keep having pressed Mod button I'm pressing \` to switch windows of application. I've observed keyboard is sending scancode of release of Super button after release of \` button.

Screen of `showkey`.
![showkey-log](https://user-images.githubusercontent.com/18653981/95745309-25df8c80-0c95-11eb-83a2-4e15ae9c0651.png)

Screen of `configuration`
![arent-mod-left-config](https://user-images.githubusercontent.com/18653981/95745372-43acf180-0c95-11eb-9834-d23ba7edee17.png)

Agent: 1.5.4
Firmware: 8.10.1 & 8.10.2
OS: Ubuntu 20.04 5.4.0-48-generic

**Comment by mondalaci** [comment]
@kareltucek I guess we can make Super+` sticky, although I'm wondering how prevalent this shortcut is.

**Comment by jsporna** [comment]
@mondalaci 
Super + \` is default shortcut in Gnome Shell for `Switch windows of an application`

![image](https://user-images.githubusercontent.com/18653981/95747833-5f19fb80-0c99-11eb-9f6b-dc925d1d4620.png)

**Comment by mondalaci** [comment]
@jsporna Thanks for letting us know!

@kareltucek Please let's make Super+backtick sticky unless you have objections.

**Comment by luteijn** [comment]
I'd still really like to see a general solution to this instead of yet another 'sticky' exception to keep in mind. Some way to leave keys explicitly held or explicitly release them when wanted. I know the USB HID interface doesn't really use key down/key up messages in the same way that ps/2, AT, XT or even MIDI serial keyboard interfaces do (making proper n-key roll-over possible for those protocols), but software and wet-ware still expects it to more or less work that way. Having a way for the UHK to emulate this behavior to at least as much as can be done within the USB protocol still feels really useful.
