### ISSUE TITLE
Left Side disconnects

### ISSUE THREAD

**Issue by lucacesare** [UltimateHackingKeyboard/firmware#443]
Hello, 
hope is not a duplicate;
as said, left side has an inconsistent connection, with the display blinking randomly as it disconnects and immediatly reconnects;
happened two times in ~2 month of usage. 
info: uhkv2 with no modules, agent version 1.5.17, latest available firmware.
Noticed that it happens when I change OS but I'm not at all sure of that.
Thanks

**Comment by mondalaci** [comment]
Hi there!

The cause of the issue is probably power-related. Please try to narrow down the cause based on points 1 to 8 of [this guide](https://ultimatehackingkeyboard.com/repair/fixing-misbehaving-keys), and let us know your findings.

This is not a bug, and it'd be easier to discuss it via email. Please shoot an email to support@ultimatehackingkeyboard.com

**Comment by lucacesare** [comment]
Okay thanks,
good to know!
Sorry and keep up the good work!
Best regards,
Luca

Il Mar 18 Gen 2022, 15:00 László Monda ***@***.***> ha
scritto:
