### ISSUE TITLE
Modifier layers emit phantom characters

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#500]
When tapping a modifier key for which there's a modifier layer defined, it often sends phantom characters. When setting backlight brightness to 0 or deleting the related modifier layer, the modifier key don't cause this issue anymore.

It's been suggested that the root cause may be a power issue, but I don't believe it's the case; Even when backlight brightness is 1, the issue reproducible just as easily as when it's 255. Also, tapping layer switcher keys, which also heavily affect key backlighting, don't emit phantom characters.

It'd be worth to fix the backlight of modifier layers, and see if it resolves the issue. By fixing, I mean that for none actions on modifier layers, the backlight should fall through, and the backlight of the base layer should be displayed, which would reflect how the actions work.

**Comment by kareltucek** [comment]
My observations:

- Constant RGB driver is not affected - only functional.
- Macro that directly toggles backlight does not cause the issue. (Not even when used on top of functional backlight.) 
- If I simply hold the modifier instead of tapping, keyboard starts producing keystrokes on its own within a few seconds.
- ~~If I count key activations in the matrices, there don't seem to be any surplus activations.~~ Actually, there are. They can be traced back to RightKeyMatrix, but ~~not to GPIO readings~~.
- Only right half is affected, namely keys 1, 8, 15, 22, 29 - that is, all increments of 7 between 0 and 35.
