### ISSUE TITLE
shared layers across keymaps - feature request

### ISSUE THREAD

**Issue by eegil** [UltimateHackingKeyboard/firmware#567]
while the concept of keymaps is quite a unique feature of UHK firmware, some layers do not really need to stay separate keymaps since they are redundant to some extent. The proposal is to have also shared layers or the option to share a specific layer across all keymaps.

**Comment by kareltucek** [comment]
I would love that too.

So far nearest functionality to that is the `holdKeymapLayer` extended command, which however induces reload of entire keymap, which is hardly ideal. I was also thinking about introducing a `replaceLayer <tgt layer (LAYERID)> <src keymap (KEYMAPID)> <src layer (LAYERID)>`, and `overlayLayer  <tgt layer (LAYERID)> <src keymap (KEYMAPID)> <src layer (LAYERID)>`. (These could then go to `$onKeymapChange` macro events.)

**Comment by mondalaci** [comment]
@eegil Please elaborate on your exact use case.

@kareltucek I've been thinking about something like you're suggesting. How exactly would the proposed commands work?

**Comment by kareltucek** [comment]
User-point of view:

- When used, target layer of current keymap is replaced or overlayed with the supplied layer. (In RAM, so the alteration will survive regular layer switching and toggling, but will get resetted when the keymap is switched forth and back. It will not survive a `holdKeymapLayer` call.)

- By overlay I mean that non-empty actions are applied. (E.g., if the source layer contains just arrows on wsad, overlaying such layer over qwerty will result in qwerty with arrows in place of wsad.)

- If the commands are put into `$onKeymapChange`, it effectively "permanently" replaces layer of such keymap with a layer of different keymap.

Developer point of view:

- The config parser is extended with a structure defining what should actually be parsed. This means that in the upper part of the call tree, the functions will get a new argument instead of current `parseDry`. The lower part of the call tree will remain mostly unchanged (i.e., either unchanged or with straightforward arguments.)

- When a command is executed, the config parser is called with a config structure which specifies which layers are to be applied, and where.

**Comment by mondalaci** [comment]
@kareltucek Thanks for elaborating! The suggested behavior and implementation sound good.

How about also having `replaceKeymap` and `overlayKeymap`?

**Comment by kareltucek** [comment]
How would `replaceKeymap` be different from `switchKeymap`?

Regarding `overlayKeymap`, I find it a bit niche and cannot imagine usecase for it, but it may make sense...

/Edit: On second thought, I would not introduce `overlayKeymap` unless there is a demandfor it.

**Comment by mondalaci** [comment]
`replaceKeymap` makes zero sense, indeed.

As for a valid use case for `overlayKeymap`, imagine having a main gaming keymap with many sub-keymaps for individual games that customize it. I think it has merit in such cases.

**Comment by kareltucek** [comment]
Sounds fair.

**Comment by eegil** [comment]
I may be wrong but I think that keymaps are a great horizontal implementation for the various keyboard layouts and operating systems such as qwerty for mac, qwerty for pc, colemak or dvorak etc, however, the other layers such as fn, mod, super, application keyboard layouts (games or apps) should have a vertical approach, shared across the keymaps, since they tend to have same mapping across. Also, the user should have the option to choose what layer should be within the context of a keymap or a generic vertical approach across selectable keymaps.

**Comment by mondalaci** [comment]
Depending on one's use case, making application-specific keymaps makes sense.

**Comment by mhantsch** [comment]
Is that really something you want to solve in the firmware, or would Agent simply copy that layer automatically to all keymaps, and save the configuration to the keyboard? When you click "Save" in Agent, it always saves the complete configuration (with all keymaps), so it could simply instantiate such "linked layers".

**Comment by mondalaci** [comment]
Both solutions have merit. The firmware implementation saves configuration space and allows advanced configuration scenarios. The [Agent copy-paste layer](https://github.com/UltimateHackingKeyboard/agent/issues/1954) approach is more intuitive. Both will be supported.
