### ISSUE TITLE
Add moduleId argument to UsbCommand_GetDeviceProperty() : DevicePropertyId_FirmwareChecksum

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#677]
Please add a `moduleId` byte argument to `UsbCommand_GetDeviceProperty()` : `DevicePropertyId_FirmwareChecksum`, so that it returns the MD5 of the right half for `0` and of the left half and modules for other values.

The above is needed for Agent to compare these values with the ones provided by `UsbCommand_GetModuleProperty()` : `ModulePropertyId_FirmwareChecksum`.

**Comment by kareltucek** [comment]
Not sure if I understand...

So you basically want right side firmware to know (and provide) checksums of the other module firmwares of the same version, is that right?

Why exactly do you want to compare these checksums instead of just comparing whether the packed checksum matches the flashed checksum or not?

**Comment by mondalaci** [comment]
This way, Agent can solely rely on the information provided by the firmware to display whether the slave firmwares are up-to-date, even if their version differs but their md5 matches.

**Comment by kareltucek** [comment]
I see, makes sense.
