### ISSUE TITLE
Missing triangle icon when recording macros

### ISSUE THREAD

**Issue by tunney** [UltimateHackingKeyboard/firmware#703]
Until the latest firmware (10.2.0) when one records a runtime macro the triangle icon lit up. Now this icon does not light up and the phrase "REC" shows on the LED display. When there are warnings in ones macros this means that the display alternates between REC, WRN, QWM — so it can be hard to determine when one is actually recording a macro.
Can the triangle be brought by for this use case?

**Comment by kareltucek** [comment]
Well, the adaptive mode led was originally stolen for that purpose, so I guess this is up to @mondalaci ...

What I can do is to shorten the flashing period, which I was thinkingnabout doing anyways 

Also, when there are warnings or errors, you are supposed to resolve them, not just ignore!

**Comment by kareltucek** [comment]
Or maybe we should simply make REC override the keymap abbreviation?

**Comment by tunney** [comment]
I think have REC override would help here.

As for resolving warnings :)
Eagerly awaiting a new firmware to get rid of the annoying WRN :)

<img width="770" alt="image" src="https://github.com/UltimateHackingKeyboard/firmware/assets/860018/8392757f-0016-4c69-8657-3746e011f643">

**Comment by kareltucek** [comment]
Ah, I see. Sorry about that!

**Comment by mondalaci** [comment]
Given that adaptive mode will be implemented eventually, I'd prefer using the triangle icon for this purpose as originally intended instead of repurposing it. I prefer the REC override solution. However, if users find repurposing the triangle icon for recordings useful, I'm not against it, but it should be explicitly set via smart macros.

I'm unsure whether it's planned, but we should disallow users to silence warnings because deprecation warnings can become deprecation errors in the future, so it's better to urge users to fix their commands.

**Comment by mhantsch** [comment]
Here's my suggestion: blinking triangle = recording; steady triangle = adaptive mode

**Comment by mondalaci** [comment]
Works for me, and it can behave the way suggested by default.

**Comment by mhantsch** [comment]
The blinking/steady solution for the triangle also helps keeping the text display uncluttered. Otherwise it starts to get overloaded with too much information. I think it's enough to show the keymap name, and ERR/WRN overload as the only exception.
