### ISSUE TITLE
v11.0.0 firmware broke mouse keys control when using it with bluetooth dongle

### ISSUE THREAD

**Issue by yihou** [UltimateHackingKeyboard/firmware#765]
I have been using a Bluetooth device from Handheld Scientific that was highly recommended from the start. 

Previously, the mouse keys were functioning properly when I connected the keyboard through a Bluetooth dongle. 

However, after updating the firmware to version 11.0.0, the mouse keys no longer respond to left and right movements, only allowing the mouse cursor to move up and down.

Do let me know any details that I can provide to assist you guys to debug the problem.

**Comment by yihou** [comment]
Updates: 

Just realised there's 11.0.2 firmware, installed and the issue persist.

I noticed that when I use a keyboard connected through a Bluetooth dongle, pressing the left and right buttons on the mouse causes the cursor to move up and down. Conversely, pressing the up and down buttons on the mouse results in scrolling. 

This issue also impacts trackball movements, causing it to move up and down when I scroll the ball left and right.
 
Here is my Mouse keymap settings: 
![CleanShot 2024-03-27 at 22 00 02](https://github.com/UltimateHackingKeyboard/firmware/assets/10841650/ae732918-8734-4280-813e-5d50b1ee3329)

**Comment by mondalaci** [comment]
This issue is indirectly caused by the following modification mentioned in the changelog of the UHK firmware 11.0.0:

> Reorder USB interfaces to achieve better compatibility with KVM switches and docking stations.

However, the updated USB interfaces of the UHK are still legit. Here's the [relevant commit](https://github.com/UltimateHackingKeyboard/firmware/commit/8f25f54d6a5666cffe87760a285338ca27c8a312).

The direct cause is that the BT-500 probably implements a non-general, device-specific USB parser that relies on the specific USB interface order of pre-11.0.0 UHK firmware versions.

We won't address the shortcomings of third-party devices. Please inform Handheld Scientific about this issue so they can update their firmware.

**Comment by yihou** [comment]
Alright, will approach Handheld Scientific then.

**Comment by asdf4w3t5** [comment]
@yihou Was this mentioned to handheld scientific? 
Do they have a solution?
It's unfortunate the UHK site recommends this device but now it doesn't work lmao

**Comment by ADevAJ** [comment]
Would like an update about this too

**Comment by yigitkonur** [comment]
Will appreciate a fix or a fork that uses BT-500 compatible USB parser configs - as downgrade is not possible now, I guess it is more needed. @mondalaci

**Comment by mondalaci** [comment]
A downgrade should be possible, according to https://github.com/UltimateHackingKeyboard/agent/issues/2361#issuecomment-2505673352

We shouldn't work around the shortcomings of third-party products, such as the USB HID parser of the BT-500. They should update their firmware if they want to support the UHK mouse USB HID interface with recent UHK firmware versions.

**Comment by G2G2G2G** [comment]
I emailed them asking about it, sent me a new one to test the BT-600

I have received it today and it works fine. It has a screen and options to switch between the usb output, bluetooth output and usb + bluetooth output. So I guess theoretically you can plug it into two different computers at once, one to usb one to bluetooth lol.
Not sure how the BT-500 was. I had the BT-400 which also got hit by this update. the same time the BT-500 did

I asked them about updating firmware of the older ones, they said:
>"There is no way for end users to upgrade the firmware. Besides, it is not productive to still mess with old models."

No idea what that actually means, I asked them to clarify but have not responded.

It seems the old models could have just been fixed with a software update, seeing as how the UHK itself was changed with just software? Seems like the case from the above posts.

So assuming UHK will never change.. "usb interfaces order", which is beyond me why that does anything and why it wasn't like that in the first place. Then the BT-600 should now work forever?
>Reorder USB interfaces to achieve better compatibility with KVM switches and docking stations.

**Comment by mondalaci** [comment]
> So assuming UHK will never change.. "usb interfaces order", which is beyond me why that does anything and why it wasn't like that in the first place. Then the BT-600 should now work forever?

Yes, it should. We don't plan to change the UHK USB descriptors, although we can't guarantee that they'll stay the same forever.
