### ISSUE TITLE
Surprising behavior of layer switch locks

### ISSUE THREAD

**Issue by TorC8** [UltimateHackingKeyboard/firmware#79]
The layer switch locks on double press of layer switch key are a nice feature (clearer documention of it might be nice at some point), but I've found they also can be a little surprising.  I would suggest that the lock should be activated only on a double quick press, but if the second press lasts more than ~.5s then assume the user was careless about initially pressing the key (or something went wrong with switch debouncing) and release the layer when the layer switch key is released.

**Comment by Hurricaaane** [comment]
I agree with this. Sometimes when I want to call the mod layer, I accidentally tap the mod key once and then then hold it.

I like the locking mechanism but I don't think it should remain locked if at least one key was pressed while a layer key is being actively held down.

**Comment by mondalaci** [comment]
Excellent idea! Wouldn't have though of this by myself. 0.5s should be a reasonable value, and maybe it'd be worth to make it customizable.

(The 0.25s delay between the taps is already customizable on the firmware level, but yet to be exposed via Agent.)

**Comment by Hurricaaane** [comment]
I wanted to add that since I got the keyboard, this has probably been the biggest gripe I had. Several times a day while programming, my keystrokes will suddenly start to do insane stuff in the IDE and I'll stop and look down at the keyboard to figure out whether it's the Fn or the Mod key that is locked.

I'll probably disable the double tap completely when the option comes, unless the new implementation of the double tap is really good. I'd rather like to configure a specific keystroke in the agent to lock a key, like Fn+Backslash to lock the Fn layer or something similar.

**Comment by mondalaci** [comment]
@Hurricaaane I agree that this was the most irritating bug of all usability-wise. Just fixed it. Please flash [firmware 8.1.1](https://github.com/UltimateHackingKeyboard/firmware/releases/tag/v8.1.1) with Agent.

I set the release timeout to 100ms which I believe is an optimal value. Eventually, I'd like this to be customizable via Agent. I've already closed this issue, but feel free to report your findings.

**Comment by MattKunze** [comment]
> Eventually, I'd like this to be customizable via Agent

Definitely would like to see this customizable as well. I think I'm in a similar situation to @Hurricaaane where I'd like it essentially disabled. The only times it gets locked for me are false positives (this doesn't happen all that often to be fair though)

**Comment by mondalaci** [comment]
@MattKunze Gotcha. This is partially implemented and should be resolved soon.
