### ISSUE TITLE
OLED display

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#832]
The UHK 80 features a 256x64 pixel OLED display with 16 grayscale levels, allowing for a world of possibilities.

As for the high-level features and structure, I have a specific vision. On the highest levels, there are so-called screens. A screen occupies the entire OLED display. The main screen contains information users usually want to see, such as the current keymap. The pairing screen could be revealed when the Bluetooth pairing code must be entered. I can't foresee all the screens that are worth creating, but you get the idea.

The main screen should have a top status bar featuring the battery charge percentages rightward and the connectivity status of the UHK between the halves and toward the host leftward. Below the status bar, we should feature the current keymap name (not just the abbreviation) and the current layer.

A widget tree backs every screen. The non-leaf nodes of a tree are widget containers, and the leaf nodes are icons or texts.

Whenever the content of the screen must be updated, the dirty flags of the current screen and widget tree nodes must be set, and the OLED updater thread must be waken up. The OLED updater thread should update the changed widgets, clear their dirty flags, and go to sleep.

Screen shifting should eventually be implemented to avoid OLED burn-in, which will reduce the usable area of the display by several pixels.

A frame buffer should back the screen content for efficient display update via SPI. I'm unsure whether double-buffering is justified.

The above is meant to provide a high-level idea of the final features I envision, but I may be missing some things, so feel free to suggest. I think the first step of the implementation should simply render a multi-line string on the display.

For having bitmap fonts, the [LVGL Online Font Converter](https://lvgl.io/tools/fontconverter) and the [SnowB Bitmap Font tool](https://snowb.org/) are the best tools I could find. 4-bit-per-pixel fonts are preferred. I'm unsure about the font size, but it should have great readability, and I'm leaning toward monospaced fonts, especially [JetBrains Mono](https://www.jetbrains.com/lp/mono/).

**Comment by kareltucek** [comment]
~~My assesment is that dirty flags system complicates the system unnecessarily, at least for the moment.~~

I have implemented the ability to draw text, widgets and screen shifting. ~~It seems to me that the important display support is finished as is.~~

~~Or should I start implementing the UI? If so, do you have some more specific idea on what screens and widgets we should implement and what they should contain?~~

~~Also, it seems to me that it would be nice to support the terminus font for logging (or more generally for small text output)(a pixel-perfect font that does not get smeared all over the place on non-retina displays). Unfortunately, this seems to be a potentially very laborous task as ttf files around there do alias for some reason, and bitmap formats are not compatible with current lvgl font based machinery. Should I invest time into that?~~

Edit: I have drawn / implemented a custom terminus-like font.

**Comment by kareltucek** [comment]
I have optimized the screen redraws so that only the changed pixels are updated. This yields a significant speedup compared to full redraws, but the display spi writes are still painfully slow[^1]:

- Redrawing the widget tree in a RAM buffer takes ~10 ms (I can significantly optimize that if need be, at the cost of increased code complexity).
- Writing the changes over spi takes around 150 ms.

~~I don't see a way to optimize this further.~~

~~I wonder if there is a way to at least mitigate the damage - e.g., implement asynchronous spi writes in order to at least free the mcu for other threads in between the updates?~~

Edit: yes, it seems that it should be possible to use asynchronous zephyr api with callbacks, which won't speed up the display update, but at least will stop blocking other threads.

[^1]: Reference is a redraw that rolls 8 lines of text, 5 chars changed per line. (A tiny 7x5 glyph font, i.e., pretty small screen update.) That is ~600 changed pixels, or 4% of screen area.

**Comment by mondalaci** [comment]
This has been implemented by and large. We'll pursue the remaining issues for concrete tasks.
