### ISSUE TITLE
Left/Right bridge.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#864]
Regarding the left/right half bridge (nus/uart connection), could you elaborate on the bigger picture?

What information we know we will want to pass between them?

Do you have idea of the protocol(s)?

How will modules be connected? (As uart is one to one, I expect each half has a separate I2C bus?)

How will be halves / modules flashed?

(I ask because I am already establishing something, without having much of an idea of what the result should be... so the sooner I have a bigger picture, the less refactoring will have to be done later...)

I am also wondering if we explicitly want to have some sort of "exchange" api on the uart/nus. E.g., with state sync, I have to wait for ack from left half, because I actually can serve data faster than left half can process them.

**Comment by mondalaci** [comment]
First, let's clarify the terminology. We mostly discuss the link protocol connecting the keyboard halves and the dongle.

(I originally wanted to write an extensive document about this topic along with other high-level topics, but it would be so time-consuming and overwhelming that it's better to explain the topics individually, such as the topics of this issue. Even then, it's quite a mouthful.)

### Link protocol data-link layer

The link protocol is special compared to other UHK protocols, such as the device protocol or the module protocol, because it has two different data-link layers: NUS (wireless) and UART (wired). Both NUS and UART can be used between the keyboard halves. Only NUS can be used between a keyboard half and the dongle, but the same abstraction is used.

On top of the data-link layer, the same messages are exchanged, but in the data-link layer, some notable differences exist:
- NUS has built-in error correction (which BLE implements), but UART hasn't. I suggest using the CRC functions of `crc16c.[ch]` that we already use for the module protocol.
- NUS has a packet abstraction, which UART lacks. You've already implemented framing for UART, but we should also have framing inside NUS packets to minimize protocol overhead.
- We may have to handle acknowledgments differently.

I think we'll be able to send about [251-byte-long packages](https://github.com/UltimateHackingKeyboard/firmware/issues/848) via NUS. Even though unused bytes are not padded and sent, the protocol overhead is still significant when sending small packets, and the bandwidth is poorly utilized, so we must encapsulate multiple messages inside one NUS package. I suggest starting NUS packages with a length byte describing the length of the first message. Then, let's insert the rest of the messages prefixed by their length bytes. We can cut the last message into two pieces if there's not enough space in the current NUS package.

As for acknowledgments regarding UART, to my knowledge, we're always notified of communication errors in `uart_callback()`, so no explicit acknowledgments should be needed. I'm unfamiliar with BLE in general and NUS specifically, as well as its API in its respect, so I'm unsure whether explicit acknowledgments are needed for NUS. If they're needed, we should be mindful of minimizing protocol overhead.

### Link protocol messages

The messages flowing through the link protocol are used for state synchronization, module messaging, and module firmware updates.

Regarding state synchronization, the idea is that the state space of the peers, including the left half, right half, and dongle, is composed of state properties. I think the most manageable way to implement the synchronization is by having an array of `syncable_property_t`, one for each `SyncablePropertyId_*` value. Then, a sync manager would keep synchronizing the properties as they become dirty. Some properties are only relevant for some peers.

Regarding module messages, we must use the modules' existing I2C protocol. We'll have to extend Zephyr [to support variable-length I2C messages](https://devzone.nordicsemi.com/f/nordic-q-a/111256/variable-length-i2c-transmissions), just as I did for the KSDK. Then, the link protocol must wrap the I2C messages.

### Firmware updates

Each half has its own I2C bus for the modules. Module firmware updates will use the above-mentioned I2C in Link encapsulation. (For the UHK 60, we used BusPal for module updates, but it's suboptimal as it requires unnecessary USB re-enumeration.)

The firmware of the left half, right half, and dongle will only be updated via USB using MCUBoot. I have to tweak some settings, but it's ready.

Do you have any more questions?

**Comment by kareltucek** [comment]
> - NUS has built-in error correction (which BLE implements), but UART hasn't. I suggest using the CRC functions of crc16c.[ch] that we already use for the module protocol.

(Yes, I planned to do this eventually, but didn't consider it high priority.)

> As for acknowledgments regarding UART, to my knowledge, we're always notified of communication errors in uart_callback(), so no explicit acknowledgments should be needed.

(In case of the state sync, I am afraid I do need left half to confirm that it has finished processing of the messages. Otherwise, UART gets jammed. In practice this means that uart_rx_buf_rsp returns EACCESS (-13)...)

(Also there are going to be dialog-like exchanges, where right half asks something and left half replies, or vice versa.)

>  Even though unused bytes are not padded and sent, the protocol overhead is still significant when sending small packets, and the bandwidth is poorly utilized, so we must encapsulate multiple messages inside one NUS package.

I doubt that there will be all that many messages, except on state changes, which are effectively amortized.

I.e., let's handle this as a low priority issue.

> Regarding state synchronization, the idea is that the state space of the peers, including the left half, right half, and dongle, is composed of state properties. I think the most manageable way to implement the synchronization is by having an array of syncable_property_t, one for each SyncablePropertyId_* value. Then, a sync manager would keep synchronizing the properties as they become dirty. Some properties are only relevant for some peers.

I think I don't understand.

> Then, the link protocol must wrap the I2C messages.

This sounds like you want to poll the left module from right half over the link protocol every 5ms or so. That's insane from bandwidth-efficiency standpoint, isn't it?

> Module firmware updates will use the above-mentioned I2C in Link encapsulation. 
> ...
> The firmware of the left half, right half, and dongle will only be updated via USB using MCUBoot. I have to tweak some settings, but it's ready.

So why flash left module via link protocol (instead of cable), if the user has to connect left half physically to the usb anyways?

> Do you have any more questions?

So what are the top priorities now (especially those I could work on)? (I mean, from the standpoint of getting near to something resembling the final product - getting all the core parts running. Optimizations and refactors can (and should be) done later (when I have better idea of the problem domain).)

Also, what is the state of Uhk80-enabled Agent?

**Comment by mondalaci** [comment]
> (In case of the state sync, I am afraid I do need left half to confirm that it has finished processing of the messages. Otherwise, UART gets jammed. In practice this means that uart_rx_buf_rsp returns EACCESS (-13)...)

Please provide examples when the left half is needed to confirm something.

> I doubt that there will be all that many messages, except on state changes, which are effectively amortized.

I should also mention that states should be resynced upon NUS-UART transitions (either way) because some states can become dirty during the transition.

The USB device protocol also suffers from the same one-message-per-packet inefficiency, and eventually, the same solution should be applied. I agree that it's not a priority.

Regarding `SyncablePropertyId_*` values, I meant that instead of hand-writing a switch with many cases, an array could contain all the synchable properties, and a general algorithm would sync the dirty property values by iterating the array.

You're right that wrapping I2C inside Link would be extremely inefficient. The I2C state machines should be implemented in the individual halves, and whenever there are updates, they should be transferred via Link.

You're also right that, given that the halves' firmware must be updated via USB anyway, we should also make the modules updatable only via USB to minimize firmware complexity.

On a related note, the device protocol will also be implemented via BLE HID, but it's low priority. In the meantime, users can use Agent via USB only. Firmware updates will only be possible via USB, however.

As for the priorities, now that the hardware is finalized, it's time to make the UHK 80 ready for testers. In about a week, Robi will start working on the agent80 repo to make Agent usable. I can think of a couple of issues. Let me create them soon.

**Comment by kareltucek** [comment]
> Please provide examples when the left half is needed to confirm something.

In UltimateHackingKeyboard/firmware-uhk80#81. If you remove the semaphores waiting for acknowledgments, UART gets jammed in the left half. (Of course, alternatively you can just ad a sleep in the right half.)

I have not checked for failure logs in the right half though. If there are any, the offending packet could be re-sent. (That is, if we remove that ASSERT which causes kernel panic...) But since I understand that UART consists of just two lines, each serving for asynchronous communication in one direction, I don't see how right half could know about left half's jammed buffers.

> Regarding SyncablePropertyId_* values, I meant that instead of hand-writing a switch with many cases, an array could contain all the synchable properties, and a general algorithm would sync the dirty property values by iterating the array.

Allright, noted.

Although, so far all stuff that I needed to sync had always special steps that had to be done on sync...

> As for the priorities, now that the hardware is finalized, it's time to make the UHK 80 ready for testers. In about a week, Robi will start working on the agent80 repo to make Agent usable. I can think of a couple of issues. Let me create them soon.

Looking forward to them!

**Comment by mondalaci** [comment]
I don't understand why UART gets jammed, and I can merge proof of concept PRs to get things going, but over time, we should strive to understand the reason deeply and implement an optimal solution. I'm concerned about such issues due to power-efficiency.

If special steps are involved, feel free to ignore my suggestion of implementing a sync state machine based on an array.

**Comment by kareltucek** [comment]
I believe that the work I am doing from its callback just takes too long.

I assume the uart isr handler is not reentrant, and so when the hardware needs next buffer, it doesn't get handled until I return from the original callback. This is too late, because the uart hardware has already missed some bytes which it should have written into the buffer.

**Comment by kareltucek** [comment]
> but over time, we should strive to understand the reason deeply and implement an optimal solution.

Well, I don't like some aspects of this either.

Although in this case I am much more upset about the acknowledges having to run from a separate thread instead of from an isr. Although this problem may be within my code. Will have to do some testing...

**Comment by mondalaci** [comment]
Maybe the workload should be queued. Zephyr has multiple solutions, each with its tradeoffs, of which we should use the lightest one. See https://docs.zephyrproject.org/latest/kernel/services/index.html#data-passing

**Comment by kareltucek** [comment]
Does it mean that we don't mind dynamic memory allocation?

If so, then it sounds as a good solution to me.

**Comment by mondalaci** [comment]
I rather wouldn't use dynamic memory allocation. I foresee using more RAM and seeing the exact amount of memory available during compilation is useful.

**Comment by kareltucek** [comment]
Well the idea of storing a possibly infinite number of elements into a fixed-length buffer feels... sort of disgusting to me?

But allright, will implement it this way.

In that case, assume that received messages are queued before being processed. What exactly should happen if the queue space runs out?

**Comment by mondalaci** [comment]
Dynamic memory allocation wouldn't provide an infinite amount of memory either.

If the queue runs out, we can fall back to the alternative dirty method mentioned earlier. I don't have a better idea.

**Comment by kareltucek** [comment]
> Dynamic memory allocation wouldn't provide an infinite amount of memory either.

Well, much closer to infinite than a buffer whose capacity you have to try to keep at lowest reasonable amount.

----

Anyway, I assume this queue to handle generic messages, not just state synchronisation, so if we run out, it is more about resigning and maybe raising kernel panic.

**Comment by mondalaci** [comment]
I'm not sure if we'd be much closer to infinite. I'm considering raising the user configuration size limit to 64K eventually, in which case, we'd have tweak some settings to fit into the available 256K and there wouldn't be much left. Do you think raising to 64K makes practical sense?

**Comment by kareltucek** [comment]
UHK80 has *only* 256K available?

> Do you think raising to 64K makes practical sense?

I would very much prefer to remain UHK60 compatible.

On the other hand, I have ran out of config space before and so had to optimize down, so it surely makes practical sense. (Especially with PerKeyRgb.)

But as for size of the configuration, we can also thinking about other ways to optimize it. Given that the RGBs take a lot of space, it would make sense to compress those...

**Comment by mondalaci** [comment]
Yes, the nRF52840 only has 256K RAM.

I'd rather keep RGB as it is. I've seen that some complained about the limited number of colors for some other keyboards with indexed colors. The 64K user configuration should fit into the RAM even without RGB indexing.

**Comment by kareltucek** [comment]
You know, compression can be easily disabled for those rare cases that use too many RGB colors. 

Majority of users would benefit from simple compression.

**Comment by mondalaci** [comment]
When you put it this way, your suggestion looks much more reasonable to me.

How many indexed colors would you allow?

**Comment by kareltucek** [comment]
To begin with 256 colors for simple serialization. 

Furthermore, we could use the first action byte to store some more bits of information. E.g., have a separate value meaning "None action, black backlight".

Like whether or not the colour is indexed, or fully enumerated, or determine something like 4 most frequent colors, and serialize these as a part of the byte.

**Comment by mondalaci** [comment]
I wouldn't like to overload the first action byte for this purpose, but wondering whether a nibble would be sufficient to store indexed colors, assuming that 16 colors would be enough for the majority of users.

**Comment by kareltucek** [comment]
Yes, that's possible too, although in that case we may need to restructure the serialization format (as color is now placed directly after every key action iirc). Or make the buffer-reading function operate on bits rather than bytes. (Which is another way to optimize down the entire config significantly.

**Comment by mondalaci** [comment]
I'm really against operating on bits rather than bytes due to the added complexity. A byte should suffice for indexed colors, after all.

Let's focus on the core of this issue and discuss other matters in dedicated issues.
