### ISSUE TITLE
Remove CurrentTime loop

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#866]
Let's remove [this loop](https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/c48ef0e46d5485acfee7fe3d06e1381bf38530c5/device/src/main.c#L104-L109) eventually as it causes tons of context switches.

**Comment by kareltucek** [comment]
> I feel uneasy about this loop, and we're digging ourselves deeper into this hole.

Lets talk about it then.

- First of all, I do intend to refactor the user logic so that it is "event driven" - doing only what needs to be done, and sleeping when nothing is needed, reacting to events that need reacting[^1]. But this does not sound as the best time for this refactor[^7].
- As for the CurrentTime part of the loop, it is a non issue. It can be refactored out of this code at least a dozen different ways, and most of them should not take much more than a couple of minutes.
- As for context switches... The best way to have as many context switches as possible is to pretend that we are running a massively parallel environment, and implement each module to have its own worker that processes its agenda and competes for CPU time :-)[^2]. The best way to *not* have as many context switches as possible to me seems to have one central event loop that will take care of stuff[^3].  I.e., this loop. I would also like to move here the functionality from some other threads[^4]. Using one central event loop for most purposes has other benefits too: 
  - allows minimizing latency
  - prevents nondeterminism in scheduling.
  - greatly simplifies thread safety issues
  - event-loop based improvements can be easily ported to UHK60[^5].
- As for this new ProcessMessages(), I am not sure if I want to leave it here this exact way. Big actions like keymap reloads should definitely be done synchronously. But that doesn't mean that every message has to be processed synchronously. So we might prefer moving this into a separate thread, and have only selected actions be triggered from the main event loop.

[^1]: The idea is to extend the EventScheduler to contain something similar to an interrupt vector, that will contain bits for things that need to be done / acted upon. It will be easy to check by a few simple instructions so the entire loop can be skipped. Actions that need to be done are then done in the optimal order.
[^2]: Afaik, our MCUs are single threaded, aren't they?
[^3]: This does not mean that I want to process everything from a central event loop. There are things that make sense to do from threads.
[^4]: E.g., key_scanner, if we don't have any more power-efficient way to detect state changes than scanning every millisecond or so.
[^5]: Which increases number of context switches.
[^7]: I think we should first get all the core parts running, and later have another run-through for refactors and optimisation.

**Comment by mondalaci** [comment]
Thanks for elaborating on this! I don't want to push you hard, as this issue is not a priority. Seeing that you know the issue and have a plan put my mind at ease.

Our MCUs, both the current ones and those planned for the foreseeable future, are single-threaded.

I should mention that I plan to port the UHK 60 firmware to Zephyr. But there's no guarantee we'll succeed, and I may have to find a specialist.
