### ISSUE TITLE
Implement relevant semaphores for report updating.

### ISSUE THREAD

**Issue by kareltucek** [UltimateHackingKeyboard/firmware#878]
@benedekkupper, how does c2usb internally work with respect to updating usb reports?

Assume that I post multiple keyboard report state changes (`keyboard_app.set_report_state`) one after another at a virtually same time (at most a few us apart). Do all those changes get reported, or does only the last report state change get reported?

If we want to be sure that all state changes get reported to the host machine, what do we need to do? (I assume wait, but for what?)

(Also, what is the mouse_app polling rate?)

Motivations:
- for this question is macro execution, where we want to report rapid keystroke sequences and want them to all get reported. We don't mind the execution to slow down according to usb polling rate.
- smooth pointer movement, at least for mouse keys, which experiments (with uhk 60) show depends on mouse interface polling rate

**Comment by benedekkupper** [comment]
The current implementation is more elaborate than it needs to be, the reason for that is UltimateHackingKeyboard/firmware-uhk80#8: due to the mismatches in thread priorities, the USB send success callback preempts the call site of the sending sometimes. To mitigate this, there's a double buffer logic with an atomic variable indexing it. When you update the status of the report, the value gets set in the top buffer. If sending the record succeeds, the buffer gets flipped, and the old top buffer's contents get copied into the new top buffer. When the sending callback arrives, it compares the two buffers, if there was a change in the top buffer, then it performs a new send right away.

**Comment by benedekkupper** [comment]
If you want to be able to pull in your fresh data in a tight sequence, what you should do is add a callout to the `in_report_sent` method, before the send_buffer call.

**Comment by benedekkupper** [comment]
> Also, what is the mouse_app polling rate?

I can only tell you this for USB:
`usb::df::hid::config(usb_mouse, speed, usb::endpoint::address(0x82), 1),` the one at the end is the poll rate in ms.
BLE is more complicated, because there is no fixed rate, it takes longer if other reports are being sent at the same time, plus all other uncertainties of radio transmission. In the best case you will get the interval that was negotiated, what you see in this log output: `BLE HID conn params: interval=%u ms, latency=%u, timeout=%u ms`, 11 being 11.25ms precisely.

**Comment by kareltucek** [comment]
I don't want to pull in fresh data. I want to prevent fresh data from overwriting any old data that have not been sent to the host yet.

Assume this pseudocode (simulating a function of a macro):
```
keyboard_app.set_report_state(<h key pressed>);
keyboard_app.set_report_state(<e key pressed>);
keyboard_app.set_report_state(<l key pressed>);
keyboard_app.set_report_state(<nothing pressed>);
keyboard_app.set_report_state(<l pressed>);
keyboard_app.set_report_state(<o key pressed>);
```
I want that to produce "hello" on screen.

According to what you say, this results in a single "o" getting printed on screen, so I need to modify the pseudocode to:

```
keyboard_app.set_report_state(<h key pressed>);
<wait till report is sent>
keyboard_app.set_report_state(<e key pressed>);
<wait till report is sent>
...
```
I am asking what to fill in the `<wait till report is sent>`.

**Comment by benedekkupper** [comment]
I'm saying the same thing, just my imagination tends towards a queue of reports that gets fetched when send is possible, instead of this busy wait style that you put here. In your busy waiting style approach, you need to compare the two buffer halves, when their contents match, the app is ready for sending the next report.

**Comment by kareltucek** [comment]
Allright, do I understand correctly that you mean following change to the c2usb code (and similar to other interfaces)?

(I am having troubles parsing the meaning of https://github.com/UltimateHackingKeyboard/firmware/issues/878)

```
void keyboard_app::in_report_sent(const std::span<const uint8_t>& data)
{
    if ((prot_ == hid::protocol::BOOT) || (rollover_ != rollover::N_KEY) ||
        (rollover_override_ != rollover::N_KEY))
    {
        auto buf_idx = keys_6kro_.indexof(data.data());
        if (!keys_6kro_.compare_swap_copy(buf_idx))
        {
            // add call to our code here (that unlocks a semaphore or something)
            send_6kro_buffer(1 - buf_idx);
        }
    }
    else
    {
        auto buf_idx = keys_nkro_.indexof(data.data());
        if (!keys_nkro_.compare_swap_copy(buf_idx))
        {
            // add call to our code here  (that unlocks a semaphore or something)
            send_nkro_buffer(1 - buf_idx);
        }
    }
}
```

Furthermore that means that we should fork c2usb and maintain its fork, is that correct?

**Comment by mondalaci** [comment]
Assuming that our use case is not unusual, c2usb should support it, and we shouldn't be forced to fork it.

**Comment by benedekkupper** [comment]
Before this conversation goes off the rails:

1. c2usb is my sole intellectual property, it was written from the ground up with two main goals: a) be as future-proof and reusable as possible b) support all use cases so far encountered on UHK 60, and now UHK 80 (namely with the support for BLE HID). I wrote it in a way that it has all the customization and extension points any project could have, but if you find it otherwise, let me know.
2. All the application specific code lives in device/src/usb folder (so outside of c2usb domain), including the `in_report_sent` calls of each `*_app`, that you'd need to modify. I would never send you to modify c2usb yourself. If you can wait until next week with this, I can add the callout to the right places.

**Comment by kareltucek** [comment]
(Yeah, I did find it suspicious... but for some reason grepping for send_buffer in uhk code didn't turn up any results - I must have made some mistake when grepping. Sorry for the misunderstanding!)

Yes, I can wait and I think I can do it on my own when I need to. Not sure when I get to this, I find it to be lower priority, but wanted to have the information around.

**Comment by kareltucek** [comment]
Thanks!
