### ISSUE TITLE
BLE mouse speed

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#890]
@benedekkupper The last commit of UltimateHackingKeyboard/firmware-uhk80#79 seems to have made BLE mouse movement much faster. It's a welcome addition because it was very slow, but now it's a bit too fast. Any idea what's going on?

We can use a multiplier internally for BLE and calculate mouse movement accordingly, but I'm wondering if a multiplier for mouse speed is specifiable on the BLE HID descriptor level.

**Comment by kareltucek** [comment]
Well, I guess the merge of master into UltimateHackingKeyboard/firmware-uhk80#79, and thus my code, is responsible for that.

Originally the usb code didn't contain a clause to disregard x/y/scrollx/scrolly during comparison, and thus was throwing most of deltas out instead of sending them to the host.

So that's what's going on. No idea about multipliers.

**Comment by mondalaci** [comment]
I don't quite understand. Please explain in simple terms.

Did the BLE code not contain your acceleration calculation previously but it does now?

**Comment by kareltucek** [comment]
When sending a keyboard report, we first compare the newly constructed report with the last sent report. If they are the same, we don't hand it over to bluetooth stack, because the computer already knows the state. 

Now assume that we do the *exact* same thing with mouse reports.

- Assume report that says `{ x = 3, y = 0, buttons = 0 }`. We hand it over to USB stack, it compares it to previous report - assume empty report - finds that it is different, and sends it to PC. Cursor moves 3 px to the right.
- Next report is `{ x = 4, y = 0, buttons = 0 }`. We hand it over to USB stack, it compares it to previous report and finds that it is different (3 doesn't equal 4 after all), and sends it to PC. Cursor moves 4 px to the right.
- Now assume that mouse keys have reached their maximum acceleration and next report is therefore again `{ x = 4, y = 0, buttons = 0 }`. We hand it over to USB stack, it compares it to previous report and finds that it is the same as the previous one, so it sends nothing to PC. Consequently, curor **doesn't** move another 4 px to the right. (But we wanted it to!)

That's how sending mouse reports was implemented until very recently, and thus all that choppiness and mouse freezes.

**Comment by kareltucek** [comment]
(Or in really simple terms, there was a bug due to which usb stack wasnt sending substantial number of reports that it should have been sending. I have fixed this bug while dealing with dongle mouse choppiness, and now eveeything was merged in master, so more mouse reports are sent (irrespectively of target) and so speed goes up.)
