### ISSUE TITLE
Ditching keymap abbreviations for OLED keyboards

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#892]
The UHK 80 and future UHKs will use OLED displays, enabling the display of full keymap names instead of the 3-letter keymap abbreviations shown on the limited LED segment display of the UHK 60 v1 and v2.

Given the above, on new keyboards, keymap abbreviations are obsolete, and I want Agent not to display them for the new keyboard models for the sake of simplicity.

Whenever keymaps are referenced in macro commands or macro events, their abbreviations would be used on non-OLED keyboards and their full name would be used on OLED keyboards.

Any show-stoppers regarding the above? How to deal with keymap and target names containing spaces?

**Comment by kareltucek** [comment]
> Any show-stoppers regarding the above?

Nothing serious I think. The ApplyConfig function uses the name to remember and lookup keymap that was active before applying the config, but in that case I guess we can allocate longer buffer on stack.

> How to deal with keymap and target names containing spaces?

I guess we will have to use strings instead of treating them as native objects. 

It also means that at many places in the codebase we will have to use two different ways to identify keymaps depending on keyboard model, which may clutter the code.

From the standpoint of smart macros, I quite like having simple abbreviations around instead of having to use full names, but I guess I can live with this decision...

**Comment by mhantsch** [comment]
> Any show-stoppers regarding the above?

Gosh, the abbreviations are very useful in macros. Please don't remove them. At least keep them for backwards compatibility. I don't want to create different configs for UHK60s and UHK80s, and **especially** I don't want to have to rewrite macros.

**Comment by mondalaci** [comment]
It's a valid concern, and I'm closing this issue.
