### ISSUE TITLE
Make CI build a release on every commit

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware#915]

**Comment by benedekkupper** [comment]
This would be a good time to refactor the versions file generation. My proposal is a python script that is invoked by cmake at configuration time.

Benefits:

1. No extra manual step is required to produce a buildable firmware image.
2. The CI can reuse an existing Zephyr / nRF build container with no extra tools needed, instead of adding npm dependency to a custom container.

Let me know if this interests you.

**Comment by mondalaci** [comment]
Sounds reasonable. Would you port the script? If so, how much time would it take?

**Comment by benedekkupper** [comment]
I can do it yes, if only someone sends me the current versions.h with inline comments about where the generated information can be collected from (as I'm not very good at reading javascript). With copilot it will be done in an hour or so.

**Comment by mondalaci** [comment]
> if only someone sends me the current versions.h with inline comments about where the generated information can be collected

@ert78gb Please provide this file to Benedek.

**Comment by ert78gb** [comment]
I have never built firmware, so I have limited information about the versioning.
There is a documentation about the versioning https://github.com/UltimateHackingKeyboard/firmware-uhk80/blob/master/VERSIONING.md

I tried to reverse engineering the build process because I am not familiar with it.

There is the `build.sh` in the root folder that do many things.
  - Calls the `scripts/make-release.mjs` that
    - based on the device platform run the `kinetis` or `nordic` build. It uses `zephyr west build` behind the scenes  in the `nordic` branch.
    - collects GitHub org and repo info via `git` . The firmware contains these information too. Based on this information the Agent download the smart macro doc.
    - reads up the `scripts/package.json` file that contains the version informations
    ```
	"firmwareVersion": "11.1.0",
    "deviceProtocolVersion": "4.10.0",
    "moduleProtocolVersion": "4.3.0",
    "userConfigVersion": "7.1.0",
    "hardwareConfigVersion": "1.0.0",
    "smartMacrosVersion": "2.4.3",
    ```
    I don't know who and when changes these information.
    - calls the `scripts/generate-versions-h-util.mjs` that generates the `shared/versions.h`

```
// Please do not edit this file by hand!
// It is to be regenerated by /scripts/generate-versions-h.js

#ifndef __VERSIONS_H__
#define __VERSIONS_H__

// Includes:

    #include "versioning.h"
    #include "slave_protocol.h"

// Variables:

    #define FIRMWARE_MAJOR_VERSION 0
    #define FIRMWARE_MINOR_VERSION 0
    #define FIRMWARE_PATCH_VERSION 0

    #define DEVICE_PROTOCOL_MAJOR_VERSION 0
    #define DEVICE_PROTOCOL_MINOR_VERSION 0
    #define DEVICE_PROTOCOL_PATCH_VERSION 0

    #define MODULE_PROTOCOL_MAJOR_VERSION 0
    #define MODULE_PROTOCOL_MINOR_VERSION 0
    #define MODULE_PROTOCOL_PATCH_VERSION 0

    #define USER_CONFIG_MAJOR_VERSION 0
    #define USER_CONFIG_MINOR_VERSION 0
    #define USER_CONFIG_PATCH_VERSION 0

    #define HARDWARE_CONFIG_MAJOR_VERSION 0
    #define HARDWARE_CONFIG_MINOR_VERSION 0
    #define HARDWARE_CONFIG_PATCH_VERSION 0

    #define SMART_MACROS_MAJOR_VERSION 0
    #define SMART_MACROS_MINOR_VERSION 0
    #define SMART_MACROS_PATCH_VERSION 0


#define GIT_REPO ""
#define GIT_TAG ""

#ifdef DEVICE_ID
char const * const DeviceMD5Checksums[DEVICE_COUNT+1] = {
    [1] = "000000000000000000000000000000000",
    [2] = "000000000000000000000000000000000",
};
#endif

char const * const ModuleMD5Checksums[ModuleId_AllCount] = {
    [1] = "000000000000000000000000000000000",
    [2] = "000000000000000000000000000000000",
    [3] = "000000000000000000000000000000000",
    [4] = "000000000000000000000000000000000",
};

#endif
```

the `shared/versions.h` file contains the md5 hash-es of the firmware of the modules and devices. The whole build process runs multiple times to generate proper md5 hashes. 
1. runs with `0` version numbers and `0` md5 hashes
2. runs with real version number and calculate md5 hashes
3.  runs with `0` version numbers and `0` md5 hashes, to restore developer setup

n.b. The `build.sh` do more things that not documented here.

I am not against about to rewrite everything because I am not developing/releasing the firmware. I have very limited knowledge about the whole firmware, but be careful because so many things happening behind the scene, many of them not listed above.

(My experience is copilot is not enough smart to identify everything and generates maintainable code. It duplicate many things and does not reuse existing codes/libs.  Generates old style code in javascript. Currently , we don't have python so the reusability will not an issue.
I think also worth to minimalize the number or languages/tools that we use for development, because every tool and language has an extra maintenance cost.
Maybe copilot will do everything within few hours, but I already spent a hour to collect the infos and maybe it will not enough and others also will spend time to review, test, use and report and fix bugs.

I just shared my concerns, but the decision is yours.)

**Comment by mondalaci** [comment]
@benedekkupper I've just realized the following:

To build the full firmware release tarball accepted by Agent, we must not only build the firmware but invoke Agent to generate the binary configuration per keyboard model, which requires Agent and all its node.js dependencies.

Given the above, I'm unsure whether the suggested porting makes sense. Does it?

**Comment by benedekkupper** [comment]
In that case it doesn’t, at least not for the CI only. I wasn’t aware of this level of complexity… I’ll still check it out briefly if this is a low hanging fruit, because for development it would still be an improvement.
