### ISSUE TITLE
Long keymap names cut on display

### ISSUE THREAD

**Issue by rpnfan** [UltimateHackingKeyboard/firmware#950]
When using long keymap descriptions (names) they are not shown correct on the UHK80 display, but cut off and shifted to the right.

That also means that the Fn symbol will not be seen any longer, when an Fn key is pressed.

Example of a long name

![image](https://github.com/user-attachments/assets/07db8ec9-8e67-4fd1-b225-fa4f1b3f62e2)

Solution could be to keep the 3 character limit for the short description on the UHK60, but extend that to more characters for the UHK80. But not use the long description on the UHK80 any longer, but also a separately defined short name).

**Comment by mondalaci** [comment]
I'd keep showing the 3-character abbreviation on the UHK 60 display due to its limited display capabilities of 3 characters.

On the UHK 80, let's show the shortened version of the keymap name. The best solution is to measure the length of the string to be displayed and cut the excess characters accordingly, but if it's complex to implement, then let's simply keep the first n characters so that all layer names fit.

When cutting the keymap name, it'd probably be worth postfixing it with "..."

**Comment by rpnfan** [comment]
I did not mean to change the 3-char abbreviation for the UHK, but to have

* long description, not restricted for UHK60 and 80
* 3-char abbreviation for UHK60
* ~ 12 (or whatever char length is possible) abbreviation for UHK80 

This has the advantage that the user decides what to display and not just assuming the description would be wanted to shown in the display.

**Comment by kareltucek** [comment]
> * ~ 12 (or whatever char length is possible) abbreviation for UHK80

Please no. Long name is still a name. 

Field for description also exist and is separate from name.
